[package]
name = "tetrs"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.26.2"
egui = "0.26.2"
priority-queue = "1.3.2"
rand = "0.8.5"

# uncomment for flamegraph generation
[profile.release]
debug = true
