[package]
name = "tetrs"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4"
priority-queue = "1.3.2"
rand = "0.8.5"

# uncomment for flamegraph generation
[profile.release]
debug = true